### ISSUE TITLE
Android sample does not work on Google Pixel 2 devices

### ISSUE THREAD

**Issue by matteinn** [Snapchat/creative-kit-sample#16]
After the redirect to the Snapchat app there is an "Something went wrong. Please try again" error, either selecting a picture/video or not.

Device info:
Pixel 2
Android 10

![Image from iOS](https://user-images.githubusercontent.com/531755/73339217-8a2dfd80-4278-11ea-8649-28b906fb0a15.jpg)

Are there any known issues?

The same sample code works just fine on many other devices, but on 3 different Google Pixel 2 devices it's not working.

**Comment by MasaYanagida** [comment]
Me, faced the same bug!!
Both `SnapCreative->send` and `SnapCreative ->sendWithCompletionHandler` not working....

```
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.myapp.android, PID: 17659
    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
        at com.google.gson.Gson.fromJson(Gson.java:888)
        at com.google.gson.Gson.fromJson(Gson.java:826)
        at com.snapchat.kit.sdk.core.networking.e.intercept(SourceFile:85)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
        at com.google.gson.Gson.fromJson(Gson.java:888) 
        at com.google.gson.Gson.fromJson(Gson.java:826) 
        at com.snapchat.kit.sdk.core.networking.e.intercept(SourceFile:85) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194) 
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.myapp.android, PID: 17659
    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
        at com.google.gson.Gson.fromJson(Gson.java:888)
        at com.google.gson.Gson.fromJson(Gson.java:826)
        at com.snapchat.kit.sdk.core.networking.e.intercept(SourceFile:85)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
```

**Comment by matteinn** [comment]
My bad, just noticed I was testing with a user not listed under the test ones. Closing
