### ISSUE TITLE
problem with android 12

### ISSUE THREAD

**Issue by Rpz75** [Snapchat/creative-kit-sample#45]
i have this problem:

java.lang.IllegalArgumentException: com.test.test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
        at com.snapchat.kit.sdk.creative.api.SnapCreativeKitApi.sendWithCompletionHandler(SourceFile:151)
        at com.snapchat.kit.sdk.creative.api.SnapCreativeKitApi.send(SourceFile:100)
        
you can correct this? 
i think in package com.snapchat.kit.sdk:creative:1.13.0

**Comment by raphaelnew** [comment]
+1 same exact issue

**Comment by melissaosullivansc** [comment]
Hi @Rpz75, this has been fixed in the 1.13.1 release. Please upgrade to this version. Thanks for reporting this issue.
